# Generated by Django 3.0.6 on 2020-07-01 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('rut', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('nombre_completo_apoderado', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
            ],
            options={
                'verbose_name': 'Apoderado',
                'verbose_name_plural': 'Apoderados',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id_institucion', models.AutoField(primary_key=True, serialize=False)),
                ('institucion', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
            },
        ),
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('adjunto_seguro', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Seguro',
                'verbose_name_plural': 'Seguros',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id_vendedor', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=200)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id_contrato', models.AutoField(max_length=200, primary_key=True, serialize=False)),
                ('fecha_contrato', models.DateField()),
                ('fecha_viaje', models.DateField()),
                ('nro_alumnos', models.IntegerField(blank=True)),
                ('adjunto_contrato', models.FileField(blank=True, null=True, upload_to='')),
                ('monto', models.IntegerField(blank=True)),
                ('institucion_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='colegio.Institucion')),
                ('nombre_completo_apoderado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='colegio.Apoderado')),
                ('seguro_id', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='colegio.Seguro')),
                ('vendedor_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='colegio.Vendedor')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
            },
        ),
    ]
