# Generated by Django 3.0.6 on 2020-07-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0002_auto_20200701_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='id_contrato',
            field=models.AutoField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
